var loginAjaxEnProceso=!1,Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(a){var b="",c,d,f,g,h,e,k=0;for(a=Base64._utf8_encode(a);k<a.length;)c=a.charCodeAt(k++),d=a.charCodeAt(k++),f=a.charCodeAt(k++),g=c>>2,c=(c&3)<<4|d>>4,h=(d&15)<<2|f>>6,e=f&63,isNaN(d)?h=e=64:isNaN(f)&&(e=64),b=b+this._keyStr.charAt(g)+this._keyStr.charAt(c)+this._keyStr.charAt(h)+this._keyStr.charAt(e);return b},decode:function(a){var b="",c,d,f,g,h,e=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,
"");e<a.length;)c=this._keyStr.indexOf(a.charAt(e++)),d=this._keyStr.indexOf(a.charAt(e++)),g=this._keyStr.indexOf(a.charAt(e++)),h=this._keyStr.indexOf(a.charAt(e++)),c=c<<2|d>>4,d=(d&15)<<4|g>>2,f=(g&3)<<6|h,b+=String.fromCharCode(c),64!=g&&(b+=String.fromCharCode(d)),64!=h&&(b+=String.fromCharCode(f));return Base64._utf8_decode(b)},_utf8_encode:function(a){a=a.replace(/\r\n/g,"\n");for(var b="",c=0;c<a.length;c++){var d=a.charCodeAt(c);128>d?b+=String.fromCharCode(d):(127<d&&2048>d?b+=String.fromCharCode(d>>
6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128))}return b},_utf8_decode:function(a){var b="",c=0,d;for(c1=c2=0;c<a.length;)d=a.charCodeAt(c),128>d?(b+=String.fromCharCode(d),c++):191<d&&224>d?(c2=a.charCodeAt(c+1),b+=String.fromCharCode((d&31)<<6|c2&63),c+=2):(c2=a.charCodeAt(c+1),c3=a.charCodeAt(c+2),b+=String.fromCharCode((d&15)<<12|(c2&63)<<6|c3&63),c+=3);return b}};
$(document).ready(function(){var a=$(location).attr("href").replace(/\/[^\/]*$/,"/");$("a[rel]").each(function(){var b=$(this).attr("href");$(this).attr("href",a+b+(-1!=b.indexOf("AID")?"&x="+getTimestamp():""))});"contexto"==window.tipoLogin&&-1!=window.location.search.indexOf("CONTRATA-SEGURO")&&(contextoGlobal="SEGURO");setTimeout(function(){$("#rut,#clave").keyup(function(a){a&&13==a.which||($("#error-messages strong").html("Datos incorrectos"),clearErrors($('form[name="ActionPersona"]')),loginAjaxEnProceso||
$("#btnAjax").prop("disabled",!1))});$("#rut").keypress(function(a){if(loginAjaxEnProceso)return!1;a=a.which;if(13==a)return loginAjax(),!1;if(31<a&&48>a||57<a&&75!=a&&107!=a)return!1});$("#clave").keypress(function(a){if(loginAjaxEnProceso)return!1;if(13==a.which)return loginAjax(),!1});$(".aCambioClave").hide();$(document).on("blur","#rut",function(){checkRutPersona($(this).val())&&formatRut($(this))});$(document).on("focus","#rut",function(){$(this).val($(this).val().replace(/[^0-9Kk]/g,""))})},
1)});function getParamUrlXs(){return window._idParXs&&-1==_idParXs.indexOf("--#ERR--")?"&FRSC="+_idParXs:""}function addParamUrlXs(a){if(a&&(-1!=a.indexOf("?AID=")||-1!=a.indexOf("&AID="))){var b=getParamUrlXs();b&&-1==a.indexOf(b)&&(-1==a.indexOf("#")?a+=b:(a=a.split("#"),a=a[0]+b+"#"+a[1]))}return a}var contextoGlobal="";
function loginAjax(){if($("#formLogin").valid()){loginAjaxEnProceso=!0;$("#btnAjax").prop("disabled",!0);var a="Process?AID=LOGINAJAX-0100&x="+getTimestamp(),b=document.getElementById("rut").value,c=b.replace(/[^0-9Kk]/g,"").replace("k","K"),b={IdPers:"1",IPCliente:"",AsyncRqUID:"",CustPermID:c,CustLoginID:c,CustLoginID2:b,SignonPswd:document.getElementById("clave").value},d="";$.ajax({url:a,data:b,type:"post",dataType:"json",async:!0,success:function(a){d=a?a.primerLogin:null;usuario=c;if("contexto"!=
window.tipoLogin)if("1"==d){callRastreoLogin("Acceso",Base64.encode(c));var b=$(".aCambioClave");b.attr("href",b.attr("href")+"&FRSC="+a.idParXs)[0].click();callRastreoLogin("FormSuccess")}else"0"==d?(callRastreoLogin("Acceso",Base64.encode(c)),top.location="Process?AID=LOGIN-0300"+(location.search?"&"+location.search.substring(1):"")+"&FRSC="+a.idParXs+"&x="+getTimestamp(),callRastreoLogin("FormSuccess")):(mostrarErrorLoginDatosIncorrectos(),$("#btnAjax").prop("disabled",!1),loginAjaxEnProceso=!1);
else-1!=window.location.search.indexOf("CONTRATA-SEGURO")?compruebaOfertaContexto(a):ejecutaLoginContexto(a)},error:function(a,b,d){procesarErrorJsonLogin(a,b,d);$("#btnAjax").prop("disabled",!1);loginAjaxEnProceso=!1}})}}var indicadorOferta;
function compruebaOfertaContexto(a){var b=document.getElementById("rut").value,c=b.replace(/[^0-9Kk]/g,"").replace("k","K"),b={IdPers:"1",IPCliente:"",AsyncRqUID:"",CustPermID:c,CustLoginID:c,CustLoginID2:b,SignonPswd:document.getElementById("clave").value};$.ajax({url:"Process?AID=OFERTACONTEXTO-0000",data:b,type:"post",dataType:"json",async:!0,success:function(b){indicadorOferta=b.ofertaSeg;ejecutaLoginContexto(a,b.ofertaSeg)},error:function(a,b,c){procesarErrorJsonLogin(a,b,c);$("#btnAjax").prop("disabled",
!1);loginAjaxEnProceso=!1}})}
function ejecutaLoginContexto(a,b){var c=document.getElementById("rut").value.replace(/[^0-9Kk]/g,"").replace("k","K"),d=a?a.primerLogin:null;"1"==d?(callRastreoLogin("Acceso",Base64.encode(c)),$(".aCambioClave").click(),c=$(".aCambioClave"),c.attr("href",c.attr("href")+"&FRSC="+a.idParXs)[0].click(),callRastreoLogin("FormSuccess")):"0"==d?"N"!=b||"SEGURO"!=contextoGlobal?(callRastreoLogin("Acceso",Base64.encode(c)),top.location="Process?AID=LOGINCONTEXTO-0100"+(location.search?"&"+location.search.substring(1):
"")+"&FRSC="+a.idParXs+"&x="+getTimestamp(),callRastreoLogin("FormSuccess")):(mostrarErrorLoginDatosSeguros(),$("#btnAjax").prop("disabled",!1),loginAjaxEnProceso=!1,logoutajax()):(mostrarErrorLoginDatosIncorrectos(),$("#btnAjax").prop("disabled",!1),loginAjaxEnProceso=!1)}function mostrarErrorLoginDatosSeguros(){muestraErrorLogin("Estimado Cliente, seg&uacute;n nuestros registros usted ya posee un Seguro de Fraude BBVA contratado.","Seguro contratado","S")}
function mostrarErrorLoginDatosIncorrectos(){muestraErrorLogin("Alguno de los datos ingresados es incorrecto.","Datos incorrectos","N")}function mostrarRecuadroError(a){$("#error-messages").show();$("#ulMensajes").show();"S"!=a&&($("#rut").addClass("inline-validation-invalid"),$("#clave").addClass("inline-validation-invalid"))}
function muestraErrorLogin(a,b,c){$("#error-messages strong").html(b);$("#ulMensajes").html("<li>"+a+"</li>");mostrarRecuadroError(c);$("#clave").val("");callRastreoLogin("FormError",a)}
function procesarErrorJsonLogin(a,b,c){var d={};a&&a.responseText&&(b=a.responseText.indexOf("/*JSON*"),c=a.responseText.indexOf("*JSON*/"),-1!=b&&-1!=c?(a=a.responseText.substring(b+7,c),d=$.parseJSON(a),$("#ulMensajes").html("<li>Error "+d.codigoError+"</li>"),$("#ulMensajes").html("<li>"+d.descripcionError+"</li>"),mostrarRecuadroError(),d&&d.estadoPeticion&&"TIMEOUT"==d.estadoPeticion&&(top.location.href=d.urlTimeout?d.urlTimeout:"Process?AID=LOGOUT_TIMEUP"),callRastreoLogin("FormError",d.descripcionError)):
mostrarErrorLoginDatosIncorrectos());return d}function getTimestamp(){return(new Date).getTime()}function addParamUrlXs(a){return a}function log(){}function callRastreoLogin(a,b){s.fa||(s.fa={va:[]});switch(a){case "Acceso":window.rastreoAccesoLogin&&rastreoAccesoLogin(b);break;case "FormSuccess":window.rastreoFormSuccessLogin&&rastreoFormSuccessLogin();break;case "FormError":window.rastreoFormErrorLogin&&rastreoFormErrorLogin(b)}}
function logoutajax(){url="?AID=LOGOUT";jQuery.ajax({url:url,data:{},type:"post",dataType:"text",async:!0,success:function(a){},error:function(a,b,c){}})};
