function rastreoFormErrorLogin(a){Rastreo_Form_Error("login","ActionPersona",_toLegalChars(a))}function rastreoFormSuccessLogin(){RastreoForm_Success("login","ActionPersona")}function rastreoFormErrorGenerarClave(a){Rastreo_Form_Error("generar clave","ActionRecuperarPsw",_toLegalChars(a))}function rastreoFormSuccessGenerarClave(){RastreoForm_Success("generar clave","ActionRecuperarPsw")}
function rastreoFormErrorFirmaContratoFilial(){Rastreo_Form_Error("firma contrato filial","firmacontratofilial","error clave coordenadas")}function rastreoFormSuccessFirmaContratoFilial(){RastreoForm_Success("firma contrato filial","firmacontratofilial")}function rastreoFormErrorAhorroInversionRealizarAbono(){Rastreo_Form_Error("ahorro inversion realizar abono","ahorroinversionrealizarabono","error clave coordenadas")}
function rastreoFormSuccessAhorroInversionRealizarAbono(){RastreoForm_Success("ahorro inversion realizar abono","ahorroinversionrealizarabono")}function rastreoFormErrorAhorroInversionAnularTransferencia(){Rastreo_Form_Error("ahorro inversion anular transferencia","ahorroinversionanulartransferencia","error clave coordenadas")}function rastreoFormSuccessAhorroInversionAnularTransferencia(){RastreoForm_Success("ahorro inversion anular transferencia","ahorroinversionanulartransferencia")}
function rastreoFormSuccessAhorroInversionConsultarMovimientos(){RastreoForm_Success("ahorro inversion consultar movimientos","ahorroinversionmovimientos")}function rastreoFormErrorAhorroInversionConsultarMovimientos(){Rastreo_Form_Error("ahorro inversion consultar movimientos","ahorroinversionmovimientos","no disponible")}function rastreoFormSuccessAhorroInversionUltimosMovimientos(){RastreoForm_Success("ahorro inversion ultimos movimientos","ahorroinversionmovimientos")}
function rastreoFormErrorAhorroInversionUltimosMovimientos(){Rastreo_Form_Error("ahorro inversion ultimos movimientos","ahorroinversionmovimientos","no disponible")}function rastreoFormSuccessAhorroInversionIngresarDinero(){RastreoForm_Success("ahorro inversion ingresar dinero","ahorroinversioningreso")}function rastreoFormErrorAhorroInversionIngresarDinero(a){Rastreo_Form_Error("ahorro inversion ingresar dinero","ahorroinversioningreso",_toLegalChars(a))}
function rastreoFormSuccessAhorroInversionProgramarIngresoDinero(){RastreoForm_Success("ahorro inversion programar ingreso dinero","ahorroinversionprogramaringreso")}function rastreoFormErrorAhorroInversionProgramarIngresoDinero(a){Rastreo_Form_Error("ahorro inversion programar ingreso dinero","ahorroinversionprogramaringreso",_toLegalChars(a))}
function rastreoFormSuccessAhorroInversionCompraventaDivisas(){RastreoForm_Success("ahorro inversion compraventa divisas","ahorroinversioncompraventadivisa")}function rastreoFormErrorAhorroInversionCompraventaDivisas(a){Rastreo_Form_Error("ahorro inversion compraventa divisas","ahorroinversioncompraventadivisa",_toLegalChars(a))}function rastreoFormSuccessAhorroInversionAccionesFirmaContrato(){RastreoForm_Success("ahorro inversion acciones firma contrato","ahorroinversioncontrato")}
function rastreoFormErrorAhorroInversionAccionesFirmaContrato(a){Rastreo_Form_Error("ahorro inversion acciones firma contrato","ahorroinversioncontrato",_toLegalChars(a))}function rastreoFormSuccessDepositoPlazoRescatar(){RastreoForm_Success("deposito plazo rescatar","depositorescatar")}function rastreoFormErrorDepositoPlazoRescatar(a){Rastreo_Form_Error("deposito plazo rescatar","depositorescatar",_toLegalChars(a))}
function rastreoFormSuccessDepositoPlazoSimular(){RastreoForm_Success("deposito plazo simular","depositosimular")}function rastreoFormErrorDepositoPlazoSimular(a){Rastreo_Form_Error("deposito plazo simular","depositosimular",_toLegalChars(a))}function rastreoFormSuccessFfmmSolicitar(){RastreoForm_Success("ahorro inversion ffmm solicitar","ffmmsolicitar")}function rastreoFormErrorFfmmSolicitar(a){Rastreo_Form_Error("ahorro inversion ffmm solicitar","ffmmsolicitar",_toLegalChars(a))}
function rastreoFormSuccessFfmmConsulta(){RastreoForm_Success("ahorro inversion ffmm consulta","ffmmconsulta")}function rastreoFormErrorFfmmConsulta(a){Rastreo_Form_Error("ahorro inversion ffmm consulta","ffmmconsulta",_toLegalChars(a))}function rastreoFormSuccessFfmmTraspasoEntreFondos(){RastreoForm_Success("ahorro inversion ffmm traspaso entre fondos","ffmmtraspaso")}
function rastreoFormErrorFfmmTraspasoEntreFondos(a){Rastreo_Form_Error("ahorro inversion ffmm traspaso entre fondos","ffmmtraspaso",_toLegalChars(a))}function rastreoFormSuccessBloquearCheques(){RastreoForm_Success("bloquear cheques","formShowCheques")}function rastreoFormErrorBloquearCheques(a){Rastreo_Form_Error("bloquear cheques","formShowCheques",_toLegalChars(a))}function rastreoFormSuccessCreditosPagarCuota(){RastreoForm_Success("creditos pagar cuota","creditocuota")}
function rastreoFormErrorCreditosPagarCuota(a){Rastreo_Form_Error("creditos pagar cuota","creditocuota",_toLegalChars(a))}function rastreoFormSuccessCuentasLineaCreditoConsulta(){RastreoForm_Success("cuentas linea credito consulta","lineacredconsulta")}function rastreoFormErrorLineaCreditoConsulta(a){Rastreo_Form_Error("cuentas linea credito consulta","lineacredconsulta",_toLegalChars(a))}
function rastreoFormSuccessCuentasConsultaHistorica(){RastreoForm_Success("cuentas consulta historica","cuentaconsulta")}function rastreoFormErrorCuentasConsultaHistorica(a){Rastreo_Form_Error("cuentas consulta historica","cuentaconsulta",_toLegalChars(a))}function rastreoFormSuccessCuentasChequesTalonariosConsulta(){RastreoForm_Success("cuentas cheques talonarios consulta","formCheques")}
function rastreoFormErrorCuentasChequesTalonariosConsulta(a){Rastreo_Form_Error("cuentas cheques talonarios consulta","formCheques",_toLegalChars(a))}function rastreoFormSuccessCuentasMovimientos(){RastreoForm_Success("cuentas movimientos","cuentaconsulta")}function rastreoFormErrorCuentasMovimientos(a){Rastreo_Form_Error("cuentas movimientos","cuentaconsulta",_toLegalChars(a))}function rastreoFormSuccessCuentasTransferencias(){RastreoForm_Success("cuentas transferencias","cuentaconsulta")}
function rastreoFormErrorCuentasTransferencias(a){Rastreo_Form_Error("cuentas transferencias","cuentaconsulta",_toLegalChars(a))}function rastreoFormSuccessCuentasMovimientosBonoFacil(){RastreoForm_Success("cuentas movimientos bono facil","cuentaconsulta")}function rastreoFormErrorCuentasMovimientosBonoFacil(a){Rastreo_Form_Error("cuentas movimientos bono facil","cuentaconsulta",_toLegalChars(a))}
function rastreoFormSuccessCuentasAsociaFB(){RastreoForm_Success("cuentas asocia facebook","cuentafb")}function rastreoFormErrorCuentasAsociaFB(a){Rastreo_Form_Error("cuentas asocia facebook","cuentafb",_toLegalChars(a))}function rastreoFormSuccessCuentasBbvaLink(){RastreoForm_Success("cuentas bbva link","cuentabbvalink")}function rastreoFormErrorCuentasBbvaLink(a){Rastreo_Form_Error("cuentas bbva link","cuentabbvalink",_toLegalChars(a))}
function rastreoFormSuccessClaveBloquear(){RastreoForm_Success("clave bloquear","fm3")}function rastreoFormErrorClaveBloquear(a){Rastreo_Form_Error("clave bloquear","fm3",_toLegalChars(a))}function rastreoFormSuccessClaveModificar(){RastreoForm_Success("clave modificar","fm2")}function rastreoFormErrorClaveModificar(a){Rastreo_Form_Error("clave modificar","fm2",_toLegalChars(a))}function rastreoFormSuccessContactosAgregar(){RastreoForm_Success("contactos agregar","form1")}
function rastreoFormErrorContactosAgregar(a){Rastreo_Form_Error("contactos agregar","form1",_toLegalChars(a))}function rastreoFormSuccessContactosModificar(){RastreoForm_Success("contactos modificar","form1")}function rastreoFormErrorContactosModificar(a){Rastreo_Form_Error("contactos modificar","form1",_toLegalChars(a))}function rastreoFormSuccessContactosEliminar(){RastreoForm_Success("contactos eliminar","form1")}
function rastreoFormErrorContactosEliminar(a){Rastreo_Form_Error("contactos eliminar","form1",_toLegalChars(a))}function rastreoFormSuccessContactosCelularAgregar(){RastreoForm_Success("contactos celular agregar","form1")}function rastreoFormErrorContactosCelularAgregar(a){Rastreo_Form_Error("contactos celular agregar","form1",_toLegalChars(a))}function rastreoFormSuccessContactosCelularEditar(){RastreoForm_Success("contactos celular editar","form1")}
function rastreoFormErrorContactosCelularEditar(a){Rastreo_Form_Error("contactos celular editar","form1",_toLegalChars(a))}function rastreoFormSuccessContactosCelularEliminar(){RastreoForm_Success("contactos celular eliminar","form1")}function rastreoFormErrorContactosCelularEliminar(a){Rastreo_Form_Error("contactos celular eliminar","form1",_toLegalChars(a))}function rastreoFormSuccessPerfilCelularModificar(a){RastreoForm_Success("perfil celular modificar",a)}
function rastreoFormErrorPerfilCelularModificar(a,b){Rastreo_Form_Error("perfil celular modificar",a,_toLegalChars(b))}function rastreoFormSuccessPerfilDireccionModificar(){RastreoForm_Success("perfil direccion modificar","fm1")}function rastreoFormErrorPerfilDireccionModificar(a){Rastreo_Form_Error("perfil direccion modificar","fm1",_toLegalChars(a))}function rastreoFormSuccessPerfilDatosPersonalesModificar(){RastreoForm_Success("perfil datos personales modificar","fm1")}
function rastreoFormErrorPerfilDatosPersonalesModificar(a){Rastreo_Form_Error("perfil datos personales modificar","fm1",_toLegalChars(a))}function rastreoFormSuccessPerfilNotificacionesModificar(){RastreoForm_Success("perfil notificaciones modificar","Servicios")}function rastreoFormErrorPerfilNotificacionesModificar(a){Rastreo_Form_Error("perfil notificaciones modificar","Servicios",_toLegalChars(a))}
function rastreoFormSuccessPerfilInversorModificar(){RastreoForm_Success("perfil inversor modificar","form1")}function rastreoFormErrorPerfilInversorModificar(a){Rastreo_Form_Error("perfil inversor modificar","form1",_toLegalChars(a))}function rastreoFormSuccessPerfilReclamos(){RastreoForm_Success("perfil reclamos","form1")}function rastreoFormErrorPerfilReclamos(a){Rastreo_Form_Error("perfil reclamos","form1",_toLegalChars(a))}
function rastreoFormSuccessDolaresCompra(){RastreoForm_Success("dolares compra","compraventadolares")}function rastreoFormErrorDolaresCompra(a){Rastreo_Form_Error("dolares compra","compraventadolares",_toLegalChars(a))}function rastreoFormSuccessDolaresVenta(){RastreoForm_Success("dolares venta","compraventadolares")}function rastreoFormErrorDolaresVenta(a){Rastreo_Form_Error("dolares venta","compraventadolares",_toLegalChars(a))}
function rastreoFormSuccessFrecuentesAgendaOtrosModificar(){RastreoForm_Success("frecuentes agenda otros modificar","agenda")}function rastreoFormErrorFrecuentesAgendaOtrosModificar(a){Rastreo_Form_Error("frecuentes agenda otros modificar","agenda",_toLegalChars(a))}function rastreoFormSuccessFrecuentesAgendaModificar(){RastreoForm_Success("frecuentes agenda modificar","agenda")}
function rastreoFormErrorFrecuentesAgendaModificar(a){Rastreo_Form_Error("frecuentes agenda modificar","agenda",_toLegalChars(a))}function rastreoFormSuccessFutbolnonstop(){RastreoForm_Success("futbol non stop","futbolns")}function rastreoFormErrorFutbolnonstop(a){Rastreo_Form_Error("futbol non stop","futbolns",_toLegalChars(a))}function rastreoFormSuccessMailEjecutivo(){RastreoForm_Success("mail ejecutivo","mailejecutivo")}
function rastreoFormErrorMailEjecutivo(a){Rastreo_Form_Error("mail ejecutivo","mailejecutivo",_toLegalChars(a))}function rastreoFormSuccessCupoLineaAumento(){RastreoForm_Success("cupo linea aumento","cupolinea")}function rastreoFormErrorCupoLineaAumento(a){Rastreo_Form_Error("cupo linea aumento","cupolinea",_toLegalChars(a))}function rastreoFormSuccessCupoTarjetaAumento(){RastreoForm_Success("cupo tarjeta aumento","cupotarjeta")}
function rastreoFormErrorCupoTarjetaAumento(a){Rastreo_Form_Error("cupo tarjeta aumento","cupotarjeta",_toLegalChars(a))}function rastreoFormSuccessOneclickAvanceTarjeta(){RastreoForm_Success("one click avance tarjeta","oneclicktarjeta")}function rastreoFormErrorOneclickAvanceTarjeta(a){Rastreo_Form_Error("one click avance tarjeta","oneclicktarjeta",_toLegalChars(a))}function rastreoFormSuccessOneclickCreditoConsumo(){RastreoForm_Success("one click credito consumo","oneclickcredito")}
function rastreoFormErrorOneclickCreditoConsumo(a){Rastreo_Form_Error("one click credito consumo","oneclickcredito",_toLegalChars(a))}function rastreoFormSuccessOneclickRefinanciamiento(){RastreoForm_Success("one click refinanciamiento","oneclickrefinancia")}function rastreoFormErrorOneclickRefinanciamiento(a){Rastreo_Form_Error("one click refinanciamiento","oneclickrefinancia",_toLegalChars(a))}
function rastreoFormSuccessOperacionesFavoritasAgregar(){RastreoForm_Success("operaciones favoritas agregar","favoritos")}function rastreoFormErrorOperacionesFavoritasAgregar(a){Rastreo_Form_Error("operaciones favoritas agregar","favoritos",_toLegalChars(a))}function rastreoFormSuccessOperacionesFavoritasEliminar(){RastreoForm_Success("operaciones favoritas eliminar","form")}
function rastreoFormErrorOperacionesFavoritasEliminar(a){Rastreo_Form_Error("operaciones favoritas eliminar","form",_toLegalChars(a))}function rastreoFormSuccessLineaCreditoPagar(){RastreoForm_Success("linea credito pagar","creditoopera")}function rastreoFormErrorLineaCreditoPagar(a){Rastreo_Form_Error("linea credito pagar","creditoopera",_toLegalChars(a))}function rastreoFormSuccessPreviredCotizacionesPago(){RastreoForm_Success("previred cotizaciones pago","previred")}
function rastreoFormErrorPreviredCotizacionesPago(a){Rastreo_Form_Error("previred cotizaciones pago","previred",_toLegalChars(a))}function rastreoFormSuccessProgramarTransferenciaAnular(){RastreoForm_Success("programar transferencia anular","programatransf")}function rastreoFormErrorProgramarTransferenciaAnular(a){Rastreo_Form_Error("programar transferencia anular","programatransf",_toLegalChars(a))}
function rastreoFormSuccessProgramarTransferenciaEnviar(){RastreoForm_Success("programar transferencia enviar","programatransf")}function rastreoFormErrorProgramarTransferenciaEnviar(a){Rastreo_Form_Error("programar transferencia enviar","programatransf",_toLegalChars(a))}function rastreoFormSuccessRecargaCelular(){RastreoForm_Success("recarga celular","formRecarga")}function rastreoFormErrorRecargaCelular(a){Rastreo_Form_Error("recarga celular","formRecarga",_toLegalChars(a))}
function rastreoFormSuccessContratarSeguro(){RastreoForm_Success("contratar seguro","formSeg")}function rastreoFormErrorContratarSeguro(a){Rastreo_Form_Error("contratar seguro","formSeg",_toLegalChars(a))}function rastreoFormSuccessSolicitudTalonario(){RastreoForm_Success("solicitud talonario","solictalonario")}function rastreoFormErrorSolicitudTalonario(a){Rastreo_Form_Error("solicitud talonario","solictalonario",_toLegalChars(a))}
function rastreoFormSuccessTarjetasOperacionesAumentoCupo(a){RastreoForm_Success("tarjetas operaciones aumento cupo",a)}function rastreoFormErrorTarjetasOperacionesAumentoCupo(a,b){Rastreo_Form_Error("tarjetas operaciones aumento cupo",a,_toLegalChars(b))}function rastreoFormSuccessTarjetasOperacionesAvanceEnLinea(){RastreoForm_Success("tarjetas operaciones avance en linea","avancelinea")}
function rastreoFormErrorTarjetasOperacionesAvanceEnLinea(a){Rastreo_Form_Error("tarjetas operaciones avance en linea","avancelinea",_toLegalChars(a))}function rastreoFormSuccessTarjetasOperacionesCanjearPuntos(){RastreoForm_Success("tarjetas operaciones canjear puntos","canjeapunto")}function rastreoFormErrorTarjetasOperacionesCanjearPuntos(a){Rastreo_Form_Error("tarjetas operaciones canjear puntos","canjeapunto",_toLegalChars(a))}
function rastreoFormSuccessTarjetasOperacionesCupoParametrico(){RastreoForm_Success("tarjetas operaciones cupo parametrico","cupoparametr")}function rastreoFormErrorTarjetasOperacionesCupoParametrico(a){Rastreo_Form_Error("tarjetas operaciones cupo parametrico","cupoparametr",_toLegalChars(a))}function rastreoFormSuccessTarjetasOperacionesPagarDeudaNacional(){RastreoForm_Success("tarjetas operaciones pagar deuda nacional","deudanac")}
function rastreoFormErrorTarjetasOperacionesPagarDeudaNacional(a){Rastreo_Form_Error("tarjetas operaciones pagar deuda nacional","deudanac",_toLegalChars(a))}function rastreoFormSuccessTarjetasOperacionesClavePinpassModificar(){RastreoForm_Success("tarjetas operaciones clave pinpass modificar","pinpass")}function rastreoFormErrorTarjetasOperacionesClavePinpassModificar(a){Rastreo_Form_Error("tarjetas operaciones clave pinpass modificar","pinpass",_toLegalChars(a))}
function rastreoFormSuccessTarjetasOperacionesRepactarDeudaPagoFlexible(){RastreoForm_Success("tarjetas operaciones repactar deuda pago flexible","repactardeuda")}function rastreoFormErrorTarjetasOperacionesRepactarDeudaPagoFlexible(a){Rastreo_Form_Error("tarjetas operaciones repactar deuda pago flexible","repactardeuda",_toLegalChars(a))}function rastreoFormSuccessTarjetasOperacionesBloquear(){RastreoForm_Success("tarjetas operaciones bloquear","tarjetaops")}
function rastreoFormErrorTarjetasOperacionesBloquear(a){Rastreo_Form_Error("tarjetas operaciones bloquear","tarjetaops",_toLegalChars(a))}function rastreoFormSuccessTarjetasOperacionesHistorico(){RastreoForm_Success("tarjetas operaciones historico","tarjetaops")}function rastreoFormErrorTarjetasOperacionesHistorico(a){Rastreo_Form_Error("tarjetas operaciones historico","tarjetaops",_toLegalChars(a))}
function rastreoFormSuccessTarjetasAporteSolidario(){RastreoForm_Success("tarjetas aporte solidario","aportesoli")}function rastreoFormSuccessTarjetasTransferencias(){RastreoForm_Success("tarjetas tranferencias","aportesoli")}function rastreoFormErrorTarjetasTransferencias(a){Rastreo_Form_Error("tarjetas transferencias","tarjetaops",_toLegalChars(a))}function rastreoFormSuccessCuentasUltimosMovimientosConsultar(){RastreoForm_Success("cuentas ultimos movimientos consultar","tarjetaops")}
function rastreoFormErrorCuentasMovimientosConsultar(a){Rastreo_Form_Error("cuentas movimientos consultar","cuentaconsulta",_toLegalChars(a))}function rastreoFormSuccessTalonariosConsultar(){RastreoForm_Success("talonarios consultar","formCheques")}function rastreoFormErrorTalonariosConsultar(a){Rastreo_Form_Error("talonarios consultar","formCheques",_toLegalChars(a))}function rastreoFormErrorAltaCorredores(a){Rastreo_Form_Error("alta corredores","fk",_toLegalChars(a))}
function rastreoFormErrorInformacionContrato(a){Rastreo_Form_Error("informacion contrato","fk",_toLegalChars(a))}function rastreoFormSuccessGuardarAlias(){RastreoForm_Success("guardar alias","alias")}function rastreoFormErrorGuardarAlias(a){Rastreo_Form_Error("guardar alias","alias",_toLegalChars(a))}function rastreoFormSuccessSeguroAutomotriz(){RastreoForm_Success("seguro automotriz","fm1")}
function rastreoFormErrorSeguroAutomotriz(a){Rastreo_Form_Error("seguro automotriz","fm1",_toLegalChars(a))}function _toLegalChars(a){return estandarizarChar(a)}function etiquetadoConsultaEstadoCuentas(){setTimeout(function(){try{s=s_gi(s_account),s.linkTrackVars="events,products",s.linkTrackEvents="event24",s.events="event24",s.products="consultas;consultas:estado de cuentas",s.tl(this,"o","consultas:estado de cuentas")}catch(a){}},0)}
function etiquetadoConsultaEECCSimple(a){setTimeout(function(){try{s=s_gi(s_account),s.linkTrackVars="events,products,eVar9",s.linkTrackEvents="event24",s.events="event24",s.eVar9=a,s.products="consultas;consultas:estado de cuentas simple",s.tl(this,"o","consultas:estado de cuentas simple")}catch(b){}},0)}
function etiquetadoCierreProductosPerfil(){setTimeout(function(){try{var a=s_gi(s_account);a.linkTrackVars="events,products";a.linkTrackEvents="event45";a.events="event45";a.products="operaciones;operaciones:solicitud de cierre2;;;;eVar11=inicio:editar mi perfil";a.tl(this,"o","operaciones:solicitud de cierre2:inicio:editar mi perfil")}catch(b){}},0)}
function etiquetadoCierreProductos(){setTimeout(function(){try{s=s_gi(s_account),s.linkTrackVars="events,products",s.linkTrackEvents="event45",s.events="event45",s.products="operaciones;operaciones:solicitud de cierre2;;;;eVar11=inicio:atencion al cliente",s.tl(this,"o","operaciones:solicitud de cierre2:inicio:atencion al cliente")}catch(a){}},0)};