var sitio=window.s_account||"bbvachilenewprod",pageNameOpcionMenuQuiero="";
$(document).ready(function(){function b(a){setTimeout(function(){try{for(var g="",c=0,g="privada:"+l,b=0;b<a.length;b++)g=g+":"+m(a[b]),c++;s.server=window.location.host;s.channel=l;s.pageType="";for(b=1;b<=g.split(":").length-1;b++)s.prop1=0<c?d(0,a):"";s.prop2=1<c?d(1,a):"";s.prop3=2<c?d(2,a):"";s.prop4=3<c?d(3,a):"";s.prop5=4<c?d(4,a):"";s.prop6=5<c?d(5,a):"";s.prop7=6<c?d(6,a):"";s.prop8=7<c?d(7,a):"";s.prop9=8<c?d(8,a):"";s.prop10=9<c?d(9,a):"";s.prop16="castellano";s.prop14="logado";s.prop15=
t?t:"";s.prop17="";s.prop18="";s.prop36="privada";s.prop37=p?p:"";s.pageName=g;s.hier1=g;s.campaign="";s.state="";s.zip="";s.events="";s.products="";s.purchaseID="";s.eVar1="";s.eVar2="";s.eVar3="";s.eVar4="";s.eVar5="";s.eVar6="";s.eVar7="";s.eVar8="";s.eVar9="";s.eVar10="";s.eVar11="";s.eVar14=s.prop14;s.eVar15=s.prop15;s.eVar16=s.prop16;s.eVar17="";s.eVar18="";s.eVar19="";s.eVar20="";s.eVar22="";s.eVar23="";s.eVar24="";s.eVar26="";s.eVar28="";s.eVar31="";s.eVar36=s.prop36;s.eVar37=s.prop37;s.eVar56=
"";s.eVar73="";s.t()}catch(e){}},0)}function d(a,g){for(var c="",b=0;b<=a&&b<g.length;b++){if(void 0===g[b])return"";c+=":"+g[b]}return l+c}function e(a){setTimeout(function(){try{s.linkTrackVars="events,eVar31",s.linkTrackEvents="event31",s.events="event31",s.eVar31=a,s.tl(!0,"o","menu contacto:click")}catch(g){}},0)}function n(){f("actualizacion de datos:redes sociales")}function f(a){setTimeout(function(){try{s.linkTrackVars="eVar28,events",s.linkTrackEvents="event28",s.events="event28",s.eVar28=
a,s.tl(this,"o",a)}catch(g){}},0)}function q(){var a=[];if($("#posicion-global").hasClass("active"))a.push("inicio");else{for(var g=$("#pMenuMiga").children(),c=0;c<g.size();c++)a.push(m(g[c].innerHTML));a[a.length-1]===a[a.length-2]&&a.pop();if("cuentas"==a[1])"transferir dinero"==a[3]&&(a[3]="transferir","mis cuentas bbva"==a[4]?a[4]="mis cuentas":"otros titulares bbva"==a[4]?a[4]="otros tit":"otros bancos"==a[4]&&(a[4]="otr bancos"));else if("tarjetas"==a[1])void 0!==a[2]&&(a[2].includes("visa")||
a[2].includes("mast")||a[2].includes("dorada")||a[2].includes("titular")?a[2]="tarjeta credito":a[2]="tarjeta debito"),void 0!==a[3]&&a[3].includes("deuda")&&(a[3]="pagar deuda");else if("creditos"===a[1])try{a[3].includes("pagar cuota")?a[3]="pagar cuota":a[3].includes("dividendo")&&(a[3]="pagar dividendo")}catch(b){}else if("ahorro e inversion"===a[1])if("Fondos mutuos"===$(".section-tabs .title-sh").text()){a[2]="ffmm";try{a[3].includes("invertir")?a[3]="invertir":a[3].includes("rescatar")?a[3]=
"rescatar":a[3].includes("traspasar")&&(a[3]="traspasar")}catch(b){}}else{if("acciones"===a[2])try{a[3].includes("realizar un abono en mi cuenta inversi")&&(a[3]="abono cuenta de inversion",a.splice(1,2))}catch(b){}}else if("ahorro e inversion"===a[1])if("Cuentas de ahorro"===$(".section-tabs .title-sh").text()){a[2]="cuentas ahorro";try{a[3].includes("consultar movimientos")?a[3]="consultar movimientos":a[3].includes("realizar transferencia")?a[3]="realizar transferencia":a[3].includes("abonar dinero")?
a[3]="abonar dinero":a[3].includes("abonar dinero periodicamente")?a[3]="abonar dinero periodicamente":a[3].includes("gestionar abonos periodicos")?a[3]="gestionar abonos periodicos":a[3].includes("consultar o cobrar vale vista")&&(a[3]="consultar o cobrar vale vista")}catch(b){}}else{if("acciones"===a[2])try{a[3].includes("realizar un abono en mi cuenta inversi")&&(a[3]="abono cuenta de inversion",a.splice(1,2))}catch(b){}}else"catalogo de productos"===a[1]&&"contratar deposito"===a[2]?(a[1]="ahorro e inversion",
a[2]="simular y tomar deposito"):"contratar deposito"===a[1]?(a[1]="ahorro e inversion",a[2]="simular y tomar deposito"):"ver catola historicas"===a[1]||"ver cartolas historicas"===a[1]?a[1]="cartolas historicas":"catalogo de productos"===a[1]&&"cartolas historicas"===a[2]&&a.splice(1,1);try{a[1].includes("realizar un abono en mi cuenta inversi")&&(a[1]="abono cuenta de inversion")}catch(b){}}4===a.length&&"catalogo de productos"===a[3]&&a.splice(2,1);pageNameOpcionMenuQuiero=a+"";return a}function m(a){var b=
document.createElement("textarea");b.innerHTML=a;a=b.value;a=a.toLowerCase().trim();a=a.replace("\u00e1","a");a=a.replace("\u00e9","e");a=a.replace("\u00ed","i");a=a.replace("\u00f3","o");a=a.replace("\u00fa","u");a=a.replace("\u00f1","ny");a=a.replace("\u00fc","u");a=a.replace(/[^a-z0-9]/g," ");return a=a.replace(".","")}var u=window.sessionStorage,r=!0;try{u.setItem("test","1"),u.removeItem("test")}catch(a){r=!1}r&&sessionStorage.setItem("estadoMenuSup","false");var t=sessionStorage.getItem("rastreo.user"),
p=function(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++){for(var c=a[b];" "==c.charAt(0);)c=c.substring(1,c.length);if(0===c.indexOf("codSegmento=")){codigo=c.substring(12,c.length);a="";switch(codigo){case "1":a="clasico";break;case "2":a="preferente";break;case "3":a="premium";break;case "4":a="transaccional";break;case "5":a="sin info";break;case "6":a="pyme";break;case "7":a="remoto";break;case "8":a="banca gente";break;case "9":a="premium bajo"}return a}}return null}(),l="";void 0!=
$(".menu-trigger").children()[0].text&&(l=$(".menu-trigger").children()[0].text.toLowerCase());r&&sessionStorage.setItem("modal","");window.rastreoPagina=b;window.modVar26=function(a){s.eVar26=a};$('img[alt="Buscar"]').on("click",function(){var a=$("input[type=search]").val();""!==a.trim()&&(s.eVar19=a,s.eVar20="",s.eVar22="general",s.events="event19")});$(".enlace-salida").on("click",function(){var a=this;setTimeout(function(){try{var b=$(a).attr("href");b.split("/");var c=s_gi(sitio);c.linkTrackVars=
"prop18,eVar18,events";c.linkTrackEvents="event18";c.prop18=b;c.eVar18=b;c.events="event18";c.tl(a,"e",b)}catch(d){}},0)});$(".enlace-descarga").on("click",function(){var a=this;setTimeout(function(){try{var b=$(a).attr("href"),c=s_gi(sitio);c.linkTrackVars="prop17,eVar17,events";c.linkTrackEvents="event17";var d=q();c.prop17=d[d.length-1]+":"+m(a.innerHTML);c.eVar17=d[d.length-1]+":"+m(a.innerHTML);c.events="event17";c.tl(a,"d",b)}catch(e){}},0)});window.descargaDocumento=function(){var a=this;setTimeout(function(){try{var b=
s_gi(sitio);b.linkTrackVars="prop17,eVar17,events";b.linkTrackEvents="event17";var c=q();b.prop17=c[c.length-2]+":"+c[c.length-2]+" "+c[c.length-1];b.eVar17=c[c.length-2]+":"+c[c.length-2]+" "+c[c.length-1];b.events="event17";b.tl(a,"d","")}catch(d){}},0)};window.enlacesVideo=function(a){var b=this;setTimeout(function(){try{var c=s_gi(sitio);c.linkTrackVars="eVar23,events";c.linkTrackEvents="event23";c.eVar23=a;c.events="event23";c.tl(b,"o","videos:reproduccion")}catch(d){}},0)};$(".top-menu").children().last().children().on("click",
function(){var a=this;setTimeout(function(){try{var b=s_gi(sitio);b.linkTrackVars="events";b.linkTrackEvents="event38";b.events="event38";sessionStorage.removeItem("rastreo.user");b.tl(a,"o","desconexion")}catch(c){}},0)});(function(){var a=$("#top-menu-atencion-cliente");a.find("a.rastreo-consultayreclamos").on("click",function(){e("consulta y reclamos")});a.children().eq(1).children().eq(1).on("click",function(){e("bloquear tarjetas")});a.children().eq(1).children().eq(2).on("click",function(){e("bloquear cheques")});
a.find("a.rastreo-sucursales-y-cajeros").on("click",function(){e("sucursales y cajeros")});a.find("a.rastreo-chat").on("click",function(){e("bbva chat")})})();(function(){$("#btDatosPer_TW").on("click",function(){n()});$("#btDatosPer_FB").on("click",function(){n()})})();window.rastreoAccesoLogin=function(a){var b=this;setTimeout(function(){try{s.linkTrackVars="events,eVar15, eVar37",s.linkTrackEvents="event22",s.events="event22",s.eVar15=a,s.prop15=a,s.eVar37=p,s.prop37=p,s.tl(b,"o","login"),sessionStorage.setItem("rastreo.user",
a)}catch(c){}},0)};window.rastreoMiPerfilModificarDatosPersonales=function(){f("actualizacion de datos:datos personales")};window.rastreoMiPerfilModificarTelefono=function(){f("actualizacion de datos:telefono")};window.rastreoMiPerfilModificarDirecciones=function(){f("actualizacion de datos:direcciones")};window.rastreoMiPerfilModificarRedesSociales=n;window.rastreoMiPerfilModificarClave=function(){f("clave de acceso")};window.rastreoMiPerfilModificarNotificacionesYAlertas=function(){f("notificaciones y alertas:configuracion de avisos")};
window.rastreoMiPerfilModificarContactoRecargaCelular=function(){f("agenda de contactos:contacto de recarga celular")};window.rastreoMiPerfilModificarContactoTransferencia=function(){f("agenda de contactos:contacto transferencia")};window.rastreoMiPerfilModificarPerfilInversor=function(){f("perfil inversor")};window.rastreoMiPerfilEnviarReclamo=function(){f("consultas y reclamos:reclamos")};window.Rastreo_error_status=function(a,b){var c=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");
c.onreadystatechange=function(){404==c.status?(s.pageName="",s.pageType="errorPage"):400<=c.status&&600>c.status&&(s.pageName="error "+b+":"+a+":"+window.location.href)}};window.Rastreo_Form_Error=function(a,b,c){setTimeout(function(){try{s.sendFormEvent("e",a,b,c)}catch(d){}},0)};window.RastreoForm_Success=function(a,b){setTimeout(function(){try{s.sendFormEvent("s",a,b),sessionStorage.setItem("rastreo.context.page",a),sessionStorage.setItem("rastreo.context.form",b)}catch(c){}},0)};window.misProductosMenuSup=
function(a,b,c,d){var e=this;setTimeout(function(){try{if("false"===sessionStorage.getItem("estadoMenuSup")){var a=s_gi(sitio);a.linkTrackVars="eVar24,eVar1,events";a.linkTrackEvents="event24";a.events="event24";a.eVar24=b;a.eVar1="privada:"+l+":"+c;a.tl(e,"o","mis productos:click");sessionStorage.setItem("estadoMenuSup","true")}}catch(d){}},0)};window.misProductos=function(a,b,c,d){var e=this;setTimeout(function(){try{var f;f="false"===sessionStorage.getItem("ACC")&&"false"===sessionStorage.getItem("AHO")&&
"false"===sessionStorage.getItem("CRE")&&"false"===sessionStorage.getItem("CTA")&&"false"===sessionStorage.getItem("DEP")&&"false"===sessionStorage.getItem("FON")&&"false"===sessionStorage.getItem("LIN")&&"false"===sessionStorage.getItem("SEG")&&"false"===sessionStorage.getItem("TAR")?!0:void 0;if(f){var h=s_gi(sitio);h.linkTrackVars="eVar24,eVar1,events";h.linkTrackEvents="event24";h.events="event24";if("flecha"==d){var v=$(a).attr("class").split(" ");f="";f="active"==v[v.length-1]?"desplegar":"plegar";
h.eVar24=b+":"+f+" widget"}else h.eVar24=b;h.eVar1="privada:"+l+":"+c;h.tl(e,"o","mis productos:click")}sessionStorage.setItem("ACC",!1);sessionStorage.setItem("AHO",!1);sessionStorage.setItem("CRE",!1);sessionStorage.setItem("CTA",!1);sessionStorage.setItem("DEP",!1);sessionStorage.setItem("FON",!1);sessionStorage.setItem("LIN",!1);sessionStorage.setItem("SEG",!1);sessionStorage.setItem("TAR",!1)}catch(m){}},0)};window.getEstados=q;window.getEstado=function(a){return q()[a]};window.funnel=function(a,
b,c,d,e,f,h,l,m){setTimeout(function(){try{var k=s_gi(sitio);k.linkTrackVars="events,products";k.linkTrackEvents=a;k.events=b;k.products=c+";"+d+";"+e+";"+f+";"+h+";"+l;k.tl(!0,"o",m)}catch(n){}},0)};window.funnelContratacion=function(a,b,c,d,e,f,h,l,m){setTimeout(function(){try{var k=s_gi(sitio);k.linkTrackVars="events,products,purchaseID";k.linkTrackEvents=a;k.events=b;k.products=c+";"+d+";"+e+";"+f+";"+h+";"+l;k.tl(!0,"o",m)}catch(n){}},0)};window.estandarizarChar=m;window.getStatusModal=function(){return sessionStorage.getItem("modal")};
$("#top-menu-client-profile").find("ul").find("li").first().on("click",function(){b(["inicio","clave acceso"])});$("#perfil-datos .nav-perfil .nav-list").children().eq(1).on("click",function(){b(["inicio","clave acceso"])});$("#top-menu-client-profile").find("ul").find("li").eq(1).on("click",function(){b(["inicio","actualizacion datos"])});$("#top-menu-client-profile .header .client-profile").find("a").on("click",function(){b(["inicio","actualizacion datos"])});$("#perfil-datos .nav-perfil .nav-list").children().eq(0).on("click",
function(){b(["inicio","actualizacion datos"])});$("#top-menu-client-profile").find("ul").find("li").last().on("click",function(){b(["inicio","notificaciones y alertas"])});$("#perfil-datos .nav-perfil .nav-list").children().eq(2).on("click",function(){b(["inicio","notificaciones y alertas"])});$("#perfil-datos .nav-perfil .nav-list").children().eq(3).on("click",function(){b(["inicio","agenda contactos"])});$("#perfil-datos .nav-perfil .nav-list").children().eq(4).on("click",function(){b(["inicio",
"perfil inversor"])});$("#perfil-datos .nav-perfil .nav-list").children().eq(5).on("click",function(){b(["inicio","consultas y reclamos"])});$("#top-menu-atencion-cliente").children().eq(1).children().eq(0).on("click",function(){b(["inicio","consultas y reclamos"])})});
function tag27(){if("home"!=etiquedatoAcceso)try{etiquedatoAcceso="NOHOME";var b=s_gi(sitio),d=pageNameOpcionMenuQuiero.split(",")[3];"personalizar"==d?d="personalizar numero de cuenta":"transferir"==d?d="transferir dinero":"recargar celular"==d?d="recarga celular":"traspasar"==d?d="traspasar entre mis fondos":"pagar dividendo"==d&&"prestamo hipotecario"==b.pageName.split(":")[4]?d="pagar dividendos":"solicitar cierre de producto"==d?d="solicitar cierre de producto":"consultar o cobrar vales vista"==
d?d="consultar o cobrar vale vista":"pagar linea de credito"==d?d="pagar linea credito":"solicitud de cierre"==d&&"tarjeta credito"==b.pageName.split(":")[4]?d="solicitar cierre de producto":"canjear puntos adelante"==d?d="canjear puntos":"rescatar depositos"==d&&"deposito a plazo"==b.pageName.split(":")[4]&&(d="rescatar");"MAS_OPCIONES"==VE.accion2&&(d="mas opciones:"+d);-1!=b.pageName.indexOf("ver puntos")&&(b.pageName="privada:personas:inicio:tarjetas");b.linkTrackVars="events,eVar1,eVar27";b.linkTrackEvents=
"event27";b.events="event27";b.eVar1=b.pageName+":"+b.pageName.split(":")[3];producto="cuenta vista"==b.pageName.split(":")[2]||"linea de credito"==b.pageName.split(":")[2]?b.pageName.split(":")[2]:"cuenta corriente"==b.pageName.split(":")[4]||"tarjeta credito"==b.pageName.split(":")[4]||"tarjeta dedito"==b.pageName.split(":")[4]||"prestamo funcionario"==b.pageName.split(":")[4]||"prestamo hipotecario"==b.pageName.split(":")[4]||"prestamo consumo"==b.pageName.split(":")[4]?b.pageName.split(":")[3]:
b.pageName.split(":")[4];if("tarjeta credito"==b.pageName.split(":")[4]||"tarjetas"==b.pageName.split(":")[3])producto="tarjetas";"cuenta ahorro"==b.pageName.split(":")[4]&&(producto="cuentas ahorro","solicitud de cierre"==d&&(d="cierre de producto"));"deposito a plazo"==b.pageName.split(":")[4]&&(producto="dap");b.eVar27=producto+":"+d;b.tl($(this),"o","quieros:click:"+d)}catch(e){console.log(e)}else"home"==etiquedatoAcceso&&(etiquedatoAcceso="NOHOME")}
function tagAhorroInversion27(b){try{var d=s_gi(sitio),e=pageNameOpcionMenuQuiero.split(",")[1];"personalizar"==e?e="personalizar numero de cuenta":"transferir"==e?e="transferir dinero":"recargar celular"==e?e="recarga celular":"traspasar"==e?e="traspasar entre mis fondos":"pagar dividendo"==e&&"prestamo hipotecario"==d.pageName.split(":")[4]?e="pagar dividendos":"solicitar cierre de producto"==e?e="solicitar cierre de producto":"consultar o cobrar vales vista"==e?e="consultar o cobrar vale vista":
"pagar linea de credito"==e?e="pagar linea credito":"solicitud de cierre"==e&&"tarjeta credito"==d.pageName.split(":")[4]?e="solicitar cierre de producto":"canjear puntos adelante"==e&&(e="canjear puntos");d.linkTrackVars="events,eVar1,eVar27";d.linkTrackEvents="event27";d.events="event27";d.eVar1=d.pageName+":"+b;d.eVar27=b+":"+e;d.tl($(this),"o","quieros:click:"+e)}catch(n){console.log(n)}};
